export const Icon = {
  MainLogo: require("../Assets/Icon/MainLogo.png"),
  BackArrow: require("../Assets/Icon/BackArrow.png"),
  Search: require("../Assets/Icon/Search.png"),
  VagLogo: require("../Assets/Icon/VagLogo.png"),
  NonVag: require("../Assets/Icon/NonVag.png"),
  KnifandSpon: require("../Assets/Icon/KnifandSpon.png"),
  PrimeryLogo: require("../Assets/Icon/PrimeryLogo.png"),
  Primium: require("../Assets/Icon/Primium.png"),
  UserProfile: require("../Assets/Icon/UserProfile.jpg"),
  Call: require("../Assets/Icon/Call.png"),
  Adders: require("../Assets/Icon/Loaction.png"),
  Massage: require("../Assets/Icon/Maage.png"),
  Star: require("../Assets/Icon/star.png"),
  Rating: require("../Assets/Icon/rating.png"),
  Rating: require("../Assets/Icon/rating.png"),
  ReviewProfile: require("../Assets/Icon/ReviewProfile.png"),
};
